version: '4.0'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/task_management
      - PORT=3000
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
